Hw02 express
tanetti/goit-nodejs-homework pull request #1
Opened 2022-12-01 21:10 UTC by tanetti

Доброго вечора, постарався зробити всі операції іммутабельно.
При створенні наступного ID як ви рекомендували в першій домашці - використав reduce(), також як ви казали дуже скорочувати та писати однією строкою не став, хоча багато чого хотілося, але розумію що так важче читати :)
Маю надію що нічого не упустив бо спішив поки світло дали :)

2022-12-02 10:12 UTC, BohdanGres requested changes
Хороша робота все чистенько і охайно)
круто що накрутив мідлвари з перевірками форматів данних, я б ще додав окрему мідлварку для перевірки айдішника з квері параметрів бо хто його знає шо туди буде летіти

2022-12-02 10:12 UTC, BohdanGres commented on controllers/contacts.js
> +      .status(404)
Порожня дата це теж дата)
це рахуеться як хороша відповідь з кодом 200 і порожнім масивом

2022-12-02 12:25 UTC, tanetti commented on controllers/contacts.js
> +      .status(404)
Доброго дня, пофіксив порожню дату, також додав PATCH роут з перевикористанням вже створеного коду для роута PUT, тільки додав схему валідації та валідую по умові в залежності від методу з запиту.

2022-12-02 20:34 UTC, tanetti commented on controllers/contacts.js
> +      .status(404)
А... ну і додав валідатор id :)

2022-12-03 14:15 UTC, BohdanGres approved these changes

2022-12-03 15:45 UTC, merged