Hw04 auth
tanetti/goit-nodejs-homework pull request #3
Opened 2023-01-05 18:23 UTC by tanetti

Доброго вечора.

2023-01-05 21:38 UTC, BohdanGres requested changes

2023-01-05 21:38 UTC, BohdanGres commented on middlewares/authHeaderValidation.js
> +    if (!user) {
забули перевірити user.token === token

2023-01-05 22:05 UTC, tanetti commented on middlewares/authHeaderValidation.js
> +    if (!user) {
Вибачаюсь, там є перевірка, можна подивитись в повній версії файла.

2023-01-06 14:32 UTC, BohdanGres commented on middlewares/authHeaderValidation.js
> +    if (!user) {
так сорі прогавив

2023-01-06 14:32 UTC, BohdanGres approved these changes

2023-01-10 08:20 UTC, merged