Hw05 avatars
tanetti/goit-nodejs-homework pull request #4
Opened 2023-01-10 22:51 UTC by tanetti

Доброго дня, подумав що у видачу юрл аватарки користувача буде доречно підставляти поточну адресу хоста апки, типу якщо хост змінится з деякої причини, видача юрл буде коректна :)

2023-01-11 07:43 UTC, BohdanGres requested changes
Загалом все чудово, ідея з хостом хороша але зазвичай роблять трохи інакше, в базі зберігається шматок урли чи взагалі тільки айдішник якийсь чи нейм а всю повну урлу склеюють з конфігів, там тримають хост + якісь можливіть префікси типу /avatar і тд. Так що раджу переробити так: в бд зберігаєш нейм а саму урлу формуєш як склейку з хоста з конфіга + велью з бази

2023-01-11 13:05 UTC, tanetti commented
Підправив, тепер якщо лінк на аватарку все ще зберігається з gravatar то видача відповідно буде лінк на аватарку gravatar, а якщо ми завантажуємо свою аватарку то в базі зберігаєтьбся тільки ім'я файлу, а при видачі пришивається - протокол, хост та префікс "avatars/". Протокол та хост беруться з реквеста, таким чином ми маємо завжди валідну адресу (якщо я вірно розумію) :)

2023-01-12 08:20 UTC, BohdanGres commented on controllers/users.js
> +      const avatarsPath = `${req.protocol}://${req.headers.host}/avatars/`;
тут має бути формування з конфігів урли бо цей процес має бути більш контрольваним 
      const avatarsPath = `${process.env.host}/avatars/`;
      з реквесту в теорії теж можна брати але це не дуже надійно + в реальних апках видача зображень зазвичай йде якимось іншим сервісом і твій хост апі і зображень буде різний

2023-01-12 08:45 UTC, tanetti commented on controllers/users.js
> +      const avatarsPath = `${req.protocol}://${req.headers.host}/avatars/`;
Оу, тепер розумію, дякую за тлумачення :)

2023-01-13 07:16 UTC, BohdanGres approved these changes

2023-01-13 11:43 UTC, merged